//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.PokemonEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Editor.PokemonEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Pokémon.
        /// </summary>
        public static string AddNewPokemon {
            get {
                return ResourceManager.GetString("AddNewPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Pokémon.
        /// </summary>
        public static string DeletePokemon {
            get {
                return ResourceManager.GetString("DeletePokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected Pokémon?.
        /// </summary>
        public static string DeletePokemonConfirm {
            get {
                return ResourceManager.GetString("DeletePokemonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Pokémon.
        /// </summary>
        public static string NewPokemonName {
            get {
                return ResourceManager.GetString("NewPokemonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string PokemonAttack {
            get {
                return ResourceManager.GetString("PokemonAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string PokemonDefense {
            get {
                return ResourceManager.GetString("PokemonDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Points.
        /// </summary>
        public static string PokemonHealthPoints {
            get {
                return ResourceManager.GetString("PokemonHealthPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Values (IV).
        /// </summary>
        public static string PokemonIndividualValues {
            get {
                return ResourceManager.GetString("PokemonIndividualValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PokemonName {
            get {
                return ResourceManager.GetString("PokemonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string PokemonNumber {
            get {
                return ResourceManager.GetString("PokemonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Type.
        /// </summary>
        public static string PokemonPrimaryType {
            get {
                return ResourceManager.GetString("PokemonPrimaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Type.
        /// </summary>
        public static string PokemonSecondaryType {
            get {
                return ResourceManager.GetString("PokemonSecondaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Attack.
        /// </summary>
        public static string PokemonSpecialAttack {
            get {
                return ResourceManager.GetString("PokemonSpecialAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Defense.
        /// </summary>
        public static string PokemonSpecialDefense {
            get {
                return ResourceManager.GetString("PokemonSpecialDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string PokemonSpeed {
            get {
                return ResourceManager.GetString("PokemonSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémon Editor.
        /// </summary>
        public static string ProjectExplorerItemName {
            get {
                return ResourceManager.GetString("ProjectExplorerItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SavePokemon {
            get {
                return ResourceManager.GetString("SavePokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémons list successfully saved.
        /// </summary>
        public static string SavePokemonConfirm {
            get {
                return ResourceManager.GetString("SavePokemonConfirm", resourceCulture);
            }
        }
    }
}
