//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.FileSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Editor.FileSystem.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory doesn&apos;t exists. Operation interrupted..
        /// </summary>
        public static string DirectoryFileOpenerDirectoryNotExistingException {
            get {
                return ResourceManager.GetString("DirectoryFileOpenerDirectoryNotExistingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string EntityAnyFileDescription {
            get {
                return ResourceManager.GetString("EntityAnyFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string EntityDirectoryDefaultFileName {
            get {
                return ResourceManager.GetString("EntityDirectoryDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project folder.
        /// </summary>
        public static string EntityDirectoryDescription {
            get {
                return ResourceManager.GetString("EntityDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        public static string EntityGenericFileDefaultFileName {
            get {
                return ResourceManager.GetString("EntityGenericFileDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string EntityProjectDefaultFileName {
            get {
                return ResourceManager.GetString("EntityProjectDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Project.
        /// </summary>
        public static string EntityProjectDescription {
            get {
                return ResourceManager.GetString("EntityProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Script.
        /// </summary>
        public static string EntityScriptDefaultFileName {
            get {
                return ResourceManager.GetString("EntityScriptDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Script.
        /// </summary>
        public static string EntityScriptDescription {
            get {
                return ResourceManager.GetString("EntityScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add the file {0}. A file with the same name already exists..
        /// </summary>
        public static string FileImporterLogMessageFileAlreadyExists {
            get {
                return ResourceManager.GetString("FileImporterLogMessageFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add the file {0}. This type is not supported..
        /// </summary>
        public static string FileImporterLogMessageFileTypeNotSupported {
            get {
                return ResourceManager.GetString("FileImporterLogMessageFileTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has not been found on the disk..
        /// </summary>
        public static string FileReaderFileNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("FileReaderFileNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSystem.
        /// </summary>
        public static string LogCategory {
            get {
                return ResourceManager.GetString("LogCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectLoader.
        /// </summary>
        public static string ProjectLoaderLoggerCategory {
            get {
                return ResourceManager.GetString("ProjectLoaderLoggerCategory", resourceCulture);
            }
        }
    }
}
